// Generated by https://quicktype.io

export interface ICategoriesResponse {
  success: boolean;
  categories: ICategory[];
}

export interface ICategory {
  _id: string;
  name: string;
  img: string;
  __v?: number;
}
