// Generated by https://quicktype.io
export interface IUserResponse {
  success: boolean;
  user: IUser;
  token: string;
  refreshToken: string;
}

export interface IUser {
  _id: string;
  email: string;
  phone: string;
  name: string;
  lastName: string;
}
